#!/bin/bash

if [ $TRILINOS_HOME ]; then
  echo "TRILINOS_HOME has already been set!"
else
  echo "TRILINOS_HOME has not been set.  Setting it!"
  export TRILINOS_HOME=`pwd`/../../..
fi

#echo
#echo "Generating doxygen documentation for moocho/src/MoochoUtilities ..."
#echo
#
#pushd ../src/MoochoUtilities/doc ; ./generate_Doxyfile ; popd
#doxygen ../src/MoochoUtilities/doc/Doxyfile
#
#echo
#echo "Generating doxygen documentation for moocho/src/IterationPack ..."
#echo
#
#pushd ../src/IterationPack/doc ; ./generate_Doxyfile ; popd
#doxygen ../src/IterationPack/doc/Doxyfile
#
#echo
#echo "Generating doxygen documentation for moocho/src/RTOpPack ..."
#echo
#
#pushd ../src/RTOpPack/doc ; ./generate_Doxyfile ; popd
#doxygen ../src/RTOpPack/doc/Doxyfile
#
#echo
#echo "Generating doxygen documentation for moocho/src/DenseLinAlgPack ..."
#echo
#
#pushd ../src/DenseLinAlgPack/doc ; ./generate_Doxyfile ; popd
#doxygen ../src/DenseLinAlgPack/doc/Doxyfile
#
#echo
#echo "Generating doxygen documentation for moocho/src/AbstractLinAlgPack ..."
#echo
#
#pushd ../src/AbstractLinAlgPack/doc ; ./generate_Doxyfile ; popd
#doxygen ../src/AbstractLinAlgPack/doc/Doxyfile
#
#echo
#echo "Generating doxygen documentation for moocho/src/NLPInterfacePack ..."
#echo
#
#pushd ../src/NLPInterfacePack/doc ; ./generate_Doxyfile ; popd
#doxygen ../src/NLPInterfacePack/doc/Doxyfile

echo
echo "Generating doxygen documentation for all of moocho as a single documentation collection ..."
echo

doxygen ../browser/doc/Doxyfile

echo
echo "Generating main moocho doxygen documentation page ..."
echo

doxygen Doxyfile

echo
echo "Generating main moocho doxygen documentation page as a PDF file ..."
echo

doxygen DoxyfileLatex
cd latex
cat refman.tex | sed 's/\({doxygen}\)/{doxygen}\\raggedright/g' > refman.tex.tmp
cp refman.tex.tmp refman.tex
make
cp refman.pdf ../html/MoochoReference.pdf
cd ..

echo
echo "Generating the overview document for MOOCHO ..."
echo

cd overview
latex MoochoOverview.tex
latex MoochoOverview.tex
dvipdft MoochoOverview
cp MoochoOverview.pdf ../html/MoochoOverview.pdf
cd ..
